### ISSUE TITLE
Issue de ejemplo

### ISSUE THREAD

**Issue by Estebaniarosario** [maestria-geotel-201902/unidad-0-asignacion-1-asig-conrstudio-issues-andresmoreta#2]
No tengo un problema concreto

**Comment by geofis** [comment]
Este issue, creado por @Estebaniarosario se encuentra en el repo equivocado. Por lo tanto, @andresmoreta, debes crear uno tú para dar por cumplida la asignación.

Por otra parte, @Estebaniarosario, supongo que tienes tu repo hecho, el cual verificaré ahora.

Imagino que estas confusiones son típicas de estas etapas de adaptación al uso de GitHub.
